// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package users

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         pgtype.UUID
	Username   string
	Email      string
	Role       string
	Otp        pgtype.Int4
	VerifiedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
